### ISSUE TITLE
binario

### ISSUE THREAD

**Issue by FabioZTessitore** [Giandomenico-bit/iterazione_c#10]
aggiornare il gitignore

**Comment by FabioZTessitore** [comment]
continuiamo?

**Comment by Giandomenico-bit** [comment]
Scusate se non ho risposto ma non ho proprio visto questa email. In questo periodo sono stato molto occupato con gli esami e quindi non ho potuto continuare con gli esercizi.

**Comment by FabioZTessitore** [comment]
nessun problema, quando puoi

**Comment by FabioZTessitore** [comment]
ciao, ho visto che hai ripreso gli esercizi, mi fa piacere. Per una correzione più veloce puoi inviare contatto telegram a fabioztessitore@gmail.com

**Comment by Giandomenico-bit** [comment]
prof. scusi ma non ho capito. Le devo inviare tramite e-mail il mio contatto telegram?

**Comment by FabioZTessitore** [comment]
Si

Il mar 23 feb 2021, 01:37 Giandomenico-bit <notifications@github.com> ha
scritto:
