### ISSUE TITLE
fattoriale

### ISSUE THREAD

**Issue by Giandomenico-bit** [Giandomenico-bit/iterazione_c#2]
prof. cosa intendete dire per convenzione di 0! = 1?

**Comment by FabioZTessitore** [comment]
E' una scelta. In teoria non avrebbe senso 0!
Ma ci permette di trattare tutti i casi di interesse (n!) senza dover distinguere la condizione `n è zero`

**Comment by Giandomenico-bit** [comment]
io sapevo il contrario! cioè sapevo che 0! è proprio dimostrato che è uguale 1. 

il fattoriale risulta così definito : 

- Passo base : n! = 1 ⇔ n = 0

- Passo induttivo : n! = n ⋅ ( n - 1 )! ⇔ n ≥ 1

In modo alternativo si può dimostrare il valore di 0! attraverso la seguente uguaglianza: 

1 = 1! = 1 ⋅ ( 1 - 1 )! = 1 ⋅ 0! = 0!

Nel calcolo combinatorio 

 I modi in cui posso ordinare n oggetti, cioè le sequenze di lunghezza n che posso realizzare con n oggetti, vengono spesso chiamati anche permutazioni! e si dimostra che è proprio n! 

se ad esempio volessimo calcolare tutte le possibili permutazioni in un insieme con cardinalità 0 ( ovvero 0 oggetti ) l’unica permutazione possibile è la permutazione vuota ( ∅ ) quindi 0! = 1.

io questo so poi non so se è corretto!

**Comment by FabioZTessitore** [comment]
quella che mostri non è una dimostrazione, ma serve a chiarire perché assegnamo valore 1 al termine 0!. Come ti dicevo è una scelta (conveniente) che facciamo. Infatti riusciamo a calcolare fattoriali e permutazioni senza dover distinguere il caso speciale dell'insieme vuoto

**Comment by Giandomenico-bit** [comment]
si e' una convenzione perché non induce a contraddizioni nelle dimostrazioni, ma in matematica non ci piace questo termine "convenzione". Ed e' per questo che molti matematici hanno cercato di spiegare il perché di questo risultato in maniera più analitica ma non incredibilmente rigorosa.
Ho visto un video, di recente, di un matematico inglese che spiega perché si arriva a questo risultato , in poche parole : 

come sappiamo il fattoriale di n e' definito come la produttoria dei primi n numeri naturali.
Quindi sicuramente sono vere le seguenti formule :

 4! = 4 * 3 * 2* 1 = 5! / 5
 3! = 3 * 2 * 1 = 4! / 4
 ... 
 quindi sorge spontaneo immaginare cosa accadrebbe se si proseguisse fino a 0, ed infatti si ha : 
 
 0! = 1! / 1 = 1

questa possiamo considerarla una dimostrazione oppure no ma così e' definito il fattoriale.

**Comment by FabioZTessitore** [comment]
Non è che si arriva al risultato, si arriva a prendere coscienza che è comodo itnerpretare così 0!

Cerchiamo di capirci, la definizione di fatoriale è: n! = n * (n-1) * ... * 1 (si ferma a 1)
Quando scrivi 0! dovresti scrivere = ??? non si sa cosa perché 0 è già più piccolo di 1.

Poi tutto il resto sono solo giustificazioni che la nostra convenzione è conveniente (infatti si trova tutto)

**Comment by Giandomenico-bit** [comment]
Si ho capito! Scusate ancora per la mia insistenza
