### ISSUE TITLE
countdown

### ISSUE THREAD

**Issue by FabioZTessitore** [Giandomenico-bit/iterazione_c#3]
perché `i` è di tipo `size_t`?

**Comment by Giandomenico-bit** [comment]
Secondo il C standard rappresenta un tipo intero senza segno. Questo tipo è raccomandato per qualsiasi variabile che rappresenta la dimensione o indice di un array

**Comment by FabioZTessitore** [comment]
Si, mi sembrava brutta l'assegnazione con una variabile int

**Comment by FabioZTessitore** [comment]
In ogni caso sono tipi che esistono solo in C/C++
Vale la pena?
