### ISSUE TITLE
due maggiori

### ISSUE THREAD

**Issue by FabioZTessitore** [Giandomenico-bit/iterazione_c#4]
non sono necessarie due variabili (`numero` e `numero2`)
Con una sola dovrebbe anche semplificarsi il codice

**Comment by Giandomenico-bit** [comment]
corretto! ma non so se ho fatto bene.

**Comment by Giandomenico-bit** [comment]
ma il programma non funziona lo stesso! o meglio non funziona su tutti i tipi di valori

**Comment by Giandomenico-bit** [comment]
d'altro canto ho pubblicato un altro programma "dueMaggiori2" che fa uso degli array e funziona perfettamente.

**Comment by FabioZTessitore** [comment]
elimina anche `temp`

**Comment by FabioZTessitore** [comment]
il programma con il vettore non ci serve in questa fase, puoi anche eliminarlo

**Comment by FabioZTessitore** [comment]
ok, adesso dai un'occhiata al file duemaggiori.c (c'è un po' di confusione dovuta a qualche conflitto non risolto)

ps. cerca di usare solo la variabile numero (numero2 è inutile)

**Comment by Giandomenico-bit** [comment]
ah va bene.

**Comment by FabioZTessitore** [comment]
cerca di usare solo la variabile numero (numero2 è inutile)

**Comment by FabioZTessitore** [comment]
non funziona

**Comment by Giandomenico-bit** [comment]
Ho provato con tutti i valori possibili. E funziona perfettamente

**Comment by Giandomenico-bit** [comment]
Ora dovrebbe funzionare, almeno spero

**Comment by FabioZTessitore** [comment]
prima di tutto, mi spieghi come lo compili?

**Comment by Giandomenico-bit** [comment]
gcc -c dueMaggiori.c -o dueMaggiori.o ma per velocizzare il processo scrivo gcc dueMaggiori.c

**Comment by FabioZTessitore** [comment]
non va bene, devi usare make (motivo per cui scrivi un Makefile). Quindi:

1. correggi il makefile come da issue
1. compila con `make dueMaggiori`
1. commit e push e ne riparliamo

**Comment by Giandomenico-bit** [comment]
ok fatto.

**Comment by FabioZTessitore** [comment]
torniamo ai maggiori. Se inserisco la sequenza 1 2 0 0 0 0 0 .. 0 il risultato è errato

**Comment by Giandomenico-bit** [comment]
si esatto avevo dimenticato l'altra variabile max2

**Comment by FabioZTessitore** [comment]
la sequenza 7 7 5 1 1 1 1 1 .. 1 non funziona

**Comment by Giandomenico-bit** [comment]
Si che funziona!

**Comment by FabioZTessitore** [comment]
Dice che i due massimi sono 7 e 5 invece di 7 e 7

Il dom 22 mar 2020, 21:08 Giandomenico-bit <notifications@github.com> ha
scritto:

**Comment by Giandomenico-bit** [comment]
Infatti questi sono i due massimi!

**Comment by FabioZTessitore** [comment]
Ma se nella sequenza ci sono due 7.

Se fossero i punteggi di una gara a chi le daresti le medaglie?

Il dom 22 mar 2020, 22:15 Giandomenico-bit <notifications@github.com> ha
scritto:

**Comment by Giandomenico-bit** [comment]
In quel caso si! ma qui stiamo identificando in una sequenza i due maggiori un massimo assoluto ed un massimo strettamente minore del primo.

**Comment by FabioZTessitore** [comment]
Da nessuna parte sta scritto che non possono esserci ripetizioni ;)

Il lun 23 mar 2020, 00:33 Giandomenico-bit <notifications@github.com> ha
scritto:

**Comment by Giandomenico-bit** [comment]
si ma quando si parla di massimo esso è necessariamente uno ed unico. Questo perché se supponiamo per assurdo che ne esistano due quindi avremo : un elemento a appartenente all’array è massimo se e solo se per ogni x appartenente all’array a >= x e analogamente avremo b con le stesse proprietà. Ma allora a >= b e b >= a

**Comment by FabioZTessitore** [comment]
Non c'è niente di errato nel tuo ragionamento ma manca la conclusione. Se a
<= b e b <= a significa che a = b.
Se parliamo di insiemi significa che sono lo stesso elemento (unico).
Ma qua non stiamo a fa' algebra. Bisogna trovare i due elementi maggiori
tra i valori dati (non è un insieme e sono ammesse le ripetizioni). Chiaro?

Il lun 23 mar 2020, 15:06 Giandomenico-bit <notifications@github.com> ha
scritto:

**Comment by Giandomenico-bit** [comment]
Si ma non ha senso. Il massimo è quell' elemento tale che : per ogni
elemento x appartenente all'insieme max >= x. Ma la stessa cosa vale per
max2 ma ciò significa che max = max2 per ogni elemento di input che
consideriamo. Quindi o questa proprietà vale per tutti gli input o
consideriamo max2 >= per ogni elemento tranne il massimo assoluto.

Il giorno lun 23 mar 2020 alle ore 07:57 Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by Giandomenico-bit** [comment]
va bene tutto chiaro

**Comment by FabioZTessitore** [comment]
Mettila così. Vuoi mettere in ordine i dati e prendere i primi due

Il lun 23 mar 2020, 15:22 Giandomenico-bit <notifications@github.com> ha
scritto:

**Comment by Giandomenico-bit** [comment]
Dopo correggo. Scusate ancora per l’insistenza

**Comment by FabioZTessitore** [comment]
nessun problema, l'importante è capirsi
