### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by FabioZTessitore** [Giandomenico-bit/iterazione_c#5]
me ne sono accorto solo ora, manca il Makefile (unico per tutti, solo con le opzioni di compilazione)

**Comment by FabioZTessitore** [comment]
quel math.h è una fesseria

**Comment by FabioZTessitore** [comment]
ricominciamo a lavorare?

**Comment by FabioZTessitore** [comment]
aggiustare please

**Comment by FabioZTessitore** [comment]
un ultimo sforzo ... togli le righe 4 e 5

**Comment by Giandomenico-bit** [comment]
dal codice dueMaggiori?

**Comment by FabioZTessitore** [comment]
no, Makefile

**Comment by Giandomenico-bit** [comment]
perché devo toglierle?

**Comment by Giandomenico-bit** [comment]
non funziona altrimenti?

**Comment by FabioZTessitore** [comment]
non hanno senso, forse volevi aggiungere un commento?
ps. il funzionamento di make verrà approfondito in seguito

**Comment by Giandomenico-bit** [comment]
Si

**Comment by FabioZTessitore** [comment]
le togliamo ste righe?

**Comment by FabioZTessitore** [comment]
mi spieghi perché continui a aggiungere cose a caso?

Nel Makefile, per il momento, devi solo mettere le opzioni di compilazione. In questo modo quando scrivi

```
make programma
```

lui lo converte in

```
gcc -Wall -ansi -pedantic .... ecc ecc 
```

**Comment by Giandomenico-bit** [comment]
mi da errore quando compilo! esce scritto : Makefile:3 : *** missing separator. Stop

**Comment by FabioZTessitore** [comment]
Nel Makefile, per il momento, ci devono essere solo le prime due righe. Poi ad essere precisi io faccio usare lo standard ansi, mentre tu vuoi usare il c99. Ma in ogni caso solo le prime due righe.
Ti consiglio di andarti a rivedere le parti in cui si parla della creazione del Makefile se non ti è chiara la faccenda
