### ISSUE TITLE
void

### ISSUE THREAD

**Issue by FabioZTessitore** [Giandomenico-bit/iterazione_c#6]
sulla storia del void nella definizione delle funzioni sono quasi sicuro che hai ragione tu. Hai qualche riferimento?

**Comment by Giandomenico-bit** [comment]
Ho studiato il linguaggio C su libro chiamato "Il linguaggio C : Fondamenti e tecniche di programmazione" Paul Deitel, Harvey Deitel.

**Comment by FabioZTessitore** [comment]
ok, provvedo ad aggiornare il lab
