### ISSUE TITLE
quadrato vuoto

### ISSUE THREAD

**Issue by FabioZTessitore** [Giandomenico-bit/iterazione_c#8]
valgono le stesse cose dette per quadrato (int invece di char e putchar invece di puts)

In più, immagina che questo programma faccia parte di un gioco e la velocità del codice sia importante. Mettere un if all'interno di un ciclo rallenta l'esecuzione. Come si potrebbe evitare?

**Comment by Giandomenico-bit** [comment]
Non saprei. Potrei mettere degli if al di sopra dei cicli o addirittura mettere dei cicli all'interno di altri cicli ma così torneremo punto e d'accapo. I cicli non sono altro che un'astrazione di un if. "Controlla" e "ripeti".

**Comment by FabioZTessitore** [comment]
no infatti, non è quella la strada

**Comment by FabioZTessitore** [comment]
immagina di disegnare il quadrato su carta (disegnando i singoli caratteri come fa il terminale).
Prova quindi a individuare i blocchi di operazioni che fai

**Comment by Giandomenico-bit** [comment]
Prof purtroppo non ho potuto fare a meno di inserire un ciclo all'interno di un altro. Non sono riuscito a trovare un metodo alternativo

**Comment by FabioZTessitore** [comment]
è perfetto così, il problema poteva essere l'if, non il ciclo che invece è necessario. Bisognava portare fuori dal ciclo di disegno la stampa della prima e dell'ultima riga che erano diverse dalle altre. Bravo
