### ISSUE TITLE
cerchio

### ISSUE THREAD

**Issue by FabioZTessitore** [Giandomenico-bit/iterazione_c#9]
quando si una un solo numero floating point, meglio usare double invece di float

**Comment by FabioZTessitore** [comment]
la stampa dei double si fa con %f
ps. nel ciclo do while, attenzione al confronto `raggio < 0`, meglio `raggio < 0.`

**Comment by Giandomenico-bit** [comment]
quando provo a stampare un double con %f mi da errore!

**Comment by FabioZTessitore** [comment]
non è vero

**Comment by Giandomenico-bit** [comment]
quando compilo il programma con make ottengo il seguente risultato : 
`warning : format "%f" expects argument of type, but argument 2 has type double * `
Risulta chiaro che questo tipo di output non è da considerarsi un vero e proprio in quanto l'eseguibile è stato creato lo stesso ma il compilatore mi consiglia di inserire lo specificatore di formato `"%lf"` al posto di `"%f"`. Io sapevo che per i double si usasse lo specificatore di formato long double oppure mi sono sbagliato?

**Comment by FabioZTessitore** [comment]
prima di tutto sei tu che hai detto che ti dava errore

Poi entrando nel dettaglio, float e double quando vengono stampati sono entrambi convertiti in double, quindi esiste un solo specificatore che è %f. Per l'input invece %f è per i float, %lf per i double.

**Comment by Giandomenico-bit** [comment]
si avete ragione! ho sbagliato io a pronunciarmi.
